### PR TITLE
Arabic Wiki background 

### PR DESCRIPTION
**Pull request by AhmedYounes94**
These are the four files needed for the background 
1- Added all the changes in the pom file
2- Added the four files in the directories
3- These files created by tag-classification framework they might need to be tested

### CODE REVIEW

**Comment by andehr** [comment]
Looks like the .idea directory needs to be put into your gitignore file; there's a lot of changes there that mess with .idea files

**Comment by andehr** [comment]
When you say the tag classification files need to be tested, are you saying that you weren't able to run these new features in Method52? I.e. using the surprising phrase detector, or the classifier?

**Comment by andehr** [comment]
What are these .iml files? Are they IDE specific? (if so, they should be ignored like the .idea files - so it doesn't mess with anyones IDE when they checkout the branch)

**Comment by AhmedYounes94** [comment]
> Looks like the .idea directory needs to be put into your gitignore file; there's a lot of changes there that mess with .idea files

So i need to add .idea to the files then commit then push again?
and when you say .idea is that hidden file in the directory of the project or you mean the general .idea file related to my IDE

**Comment by AhmedYounes94** [comment]
> When you say the tag classification files need to be tested, are you saying that you weren't able to run these new features in Method52? I.e. using the surprising phrase detector, or the classifier?

Yeah i couldnt test it because the method 52 project still not working because of the servlet error i mentioned in the pull request

**Comment by AhmedYounes94** [comment]
> What are these .iml files? Are they IDE specific? (if so, they should be ignored like the .idea files - so it doesn't mess with anyones IDE when they checkout the branch)

i dont really know which iml files you are talking about i didnt add them into the project they might came from cloning the repo because i dont remember creating any iml files or they might has been added automatically be IDE

**Comment by andehr** [comment]
> > Looks like the .idea directory needs to be put into your gitignore file; there's a lot of changes there that mess with .idea files
> 
> So i need to add .idea to the files then commit then push again?
> and when you say .idea is that hidden file in the directory of the project or you mean the general .idea file related to my IDE

Basically, the files in `.idea` need to be *removed* from the git repo, so they don't mess with anyone elses `.idea` directory when they check out this branch. 

You can remove the folder from a git repo like this:

`git rm -r --cached .idea` 

This will not delete the folder from the computer, only remove it from the git index. Then you can commit and push that change.

To ignore files like this in the future, you can make a file called `.gitignore` in the project's root directory with a line in it:
`.idea`.

**Comment by andehr** [comment]
> > What are these .iml files? Are they IDE specific? (if so, they should be ignored like the .idea files - so it doesn't mess with anyones IDE when they checkout the branch)
> 
> i dont really know which iml files you are talking about i didnt add them into the project they might came from cloning the repo because i dont remember creating any iml files or they might has been added automatically be IDE

The file called `wiki-sample.iml` is commited to the git repo on this branch. Should it also be removed?

**Comment by andehr** [comment]
> > When you say the tag classification files need to be tested, are you saying that you weren't able to run these new features in Method52? I.e. using the surprising phrase detector, or the classifier?
> 
> Yeah i couldnt test it because the method 52 project still not working because of the servlet error i mentioned in the pull request

Ah we need to get you running - you should be able to test it. When I look at https://github.com/CASM-Consulting/method52/pull/1622
I don't see any mention of Servlet Error?
I do see that no component showed up though. This is probably because a new plan/user needs to be assigned to a component plan (which determines which components a M52 plan can see).

You need to login in as "office" and add your role/plan to the "unrestricted" component group. So you can see all components. If you haven't already made a user and a role/plan, for your local Method52 instance, then do that first at the top of the page, by filling out user, password, and role, then clicking "add user/role".

It's a little odd, you essentially have to click any other "unrestricted" group (might be "__no_owner__") then change the dropdown to your role and click "add role".
ezgif com-video-to-gif (1)

**Comment by AhmedYounes94** [comment]
> > > What are these .iml files? Are they IDE specific? (if so, they should be ignored like the .idea files - so it doesn't mess with anyones IDE when they checkout the branch)
> > 
> > 
> > i dont really know which iml files you are talking about i didnt add them into the project they might came from cloning the repo because i dont remember creating any iml files or they might has been added automatically be IDE
> 
> The file called `wiki-sample.iml` is commited to the git repo on this branch. Should it also be removed?

oh okay i will have a look at that

**Comment by AhmedYounes94** [comment]
The last commit i added "5b0b035" didnt add  two files somehow i will make another commit

**Comment by AhmedYounes94** [comment]
Now all the repos are up to date i am ready to revise

**Pull request merged**
